### ISSUE TITLE
Copy MX-rack to plate. Duplicate plate

### ISSUE THREAD

**Issue by dahlbma** [dahlbma/cello#18]
- [x] Add "Copy rack to plate" button in the "Microtubes->Get Rack" screen. This will create a new 96 well plate and then copy the Rack layout to the new plate
- [x] Add "Duplicate plate" button to the "Plates->Manage Plates" screen. This will create a new plate with the same size as the originl plate and then copy well by well to the new plate.

**Comment by ChrillePille** [comment]
Task 1 "Copy rack to plate" was implemented in bf991d3f09b28eeacba01f31229415f695a46df4

**Comment by dahlbma** [comment]
- [x] Add a "Volume" editBox, the "Copy to Plate" button should only be enabled when there is both a valid rack and a volume available.

**Comment by ChrillePille** [comment]
Volume input and corresponding logic added in 04e487280665cb12852aad2affec14cd074a4d5a

**Comment by ChrillePille** [comment]
Implemented in f2597dda013bc476bba7ad5921cb1ff327552333
